#include"onlineplay.h"
OnlinePlay::OnlinePlay()
{
    begin_->setDisabled(true);
    connect(this,&OnlinePlay::get_key,this,[=](){
        begin_->setDisabled(false);
    });
    connect(this,&OnlinePlay::game_end,this,[=]()
    {
        begin_->setDisabled(true);
    });
}
